from aiogram.fsm.state import StatesGroup, State


class Tasks(StatesGroup):
    task_1 = State()
    task_2 = State()
    task_3 = State()
    task_4 = State()
    task_5 = State()
    task_6 = State()
    task_7 = State()
    task_8 = State()
    task_9 = State()
    task_10 = State()
    task_11 = State()
    task_12 = State()
    task_13 = State()
    task_14 = State()
    task_15 = State()
    task_16 = State()
    task_17 = State()
    task_18 = State()
    task_19 = State()
    task_20 = State()
    task_21 = State()
    task_22 = State()
    task_23 = State()
    task_24 = State()
    task_25 = State()
    results = State()
